# Generated by Django 5.2 on 2026-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=25, unique=True),
        ),
    ]
