# Generated by Django 5.2 on 2026-06-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_app', '0002_order_transaction_id_alter_order_order_id'),
        ('products_app', '0003_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservations',
                                    to='products_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
