# Generated by Django 5.2 on 2026-06-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order_app', '0003_alter_inventoryreservation_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
