# Generated by Django 5.2 on 2026-06-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products_app.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
