# Generated by Django 5.2 on 2026-06-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_product_parent_product_variant_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'parent', 'variant_name')},
        ),
    ]
