from django.urls import reverse
from django.contrib.auth import get_user_model
from rest_framework.test import APITestCase
from rest_framework import status
from cart.models import Cart, CartItem
from product.models import Category, Product

User = get_user_model()

class CartIntegrationTests(APITestCase):
    """
    Integration tests for the cart application.
    Covers automatic cart creation, total cost calculations, and API endpoint behaviors 
    for retrieving, adding, and removing items.
    """
    def setUp(self):
        """
        Set up the testing environment with dummy users, categories, 
        products, and fetch the automatically created cart.
        """
        # Create test users
        self.user = User.objects.create_user(email="user@uzi.com", password="123", is_active=True)
        self.other_user = User.objects.create_user(email="other@uzi.com", password="123", is_active=True)

        # Create test products
        self.category = Category.objects.create(name="phone", slug="phone")
        self.product1 = Product.objects.create(
            name="iphone 17", price=1000, stock=5, show=True, category=self.category)
        self.product2 = Product.objects.create(
            name="Galaxy S26", price=800, stock=10, show=True, category=self.category)
        
        # گونه قابل خرید جدا از محصول پایه ساخته می‌شود تا محدودیت API سبد آزموده شود.
        self.variant_product = Product.objects.create(
            name="iphone 17", variant_name="Black - 256GB", parent=self.product1,
            price=1000, stock=5, show=True, category=self.category)
        
        # Retrieve the cart generated by the post_save signal
        self.cart = Cart.objects.get(user=self.user)

    def test_cart_created_automatically_on_user_creation(self):
        """Verify that a Cart instance is automatically generated when a new User is created."""
        self.assertTrue(Cart.objects.filter(user=self.user).exists())
        self.assertEqual(self.cart.user, self.user)

    def test_cart_get_total_cost_calculation(self):
        """Ensure the cart accurately calculates the total cost of all its items."""
        # این سناریو مستقیماً مدل را می‌آزماید و از اعتبارسنجی view افزودن به سبد عبور نمی‌کند.
        CartItem.objects.create(cart=self.cart, product=self.product1, quantity=1)
        CartItem.objects.create(cart=self.cart, product=self.product2, quantity=2)

        self.assertEqual(self.cart.get_total_cost(), 2600)

    def test_cart_detail_view(self):
        """Test that an authenticated user can successfully retrieve their cart details."""
        self.client.force_authenticate(user=self.user)
        url = reverse("cart_detail")

        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn("items", response.data)
        self.assertIn("total_cost", response.data)

    def test_cart_add_new_item(self):
        """Verify that a user can add a completely new product to their cart."""
        self.client.force_authenticate(user=self.user)
        url = reverse("cart_add_item")

        data = {
            "product_uuid": str(self.variant_product.uuid),
            "quantity": 2
        }
        response = self.client.post(url, data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(CartItem.objects.count(), 1)
        self.assertEqual(CartItem.objects.first().quantity, 2)

    def test_cart_add_existing_item_increments_quantity(self):
        """Ensure that adding an already existing product simply increments its quantity."""
        CartItem.objects.create(cart=self.cart, product=self.variant_product, quantity=1)
        
        self.client.force_authenticate(user=self.user)
        url = reverse("cart_add_item")
        data = {
            "product_uuid": str(self.variant_product.uuid),
            "quantity": 3
        }
        response = self.client.post(url, data, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(CartItem.objects.count(), 1)
        self.assertEqual(CartItem.objects.first().quantity, 4)

    def test_cart_add_invalid_product_returns_404(self):
        """Test that attempting to add a non-existent product returns a 404 Not Found error."""
        self.client.force_authenticate(user=self.user)
        url = reverse('cart_add_item')

        data = {"product_uuid": "12345678-1234-5678-1234-567812345678", "quantity": 1}
        response = self.client.post(url, data, format='json')

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_cart_remove_item_success(self):
        """Verify that a user can successfully remove an existing item from their cart."""
        CartItem.objects.create(cart=self.cart, product=self.variant_product, quantity=1)

        self.client.force_authenticate(user=self.user)
        url = reverse('cart_remove_item')
        data = {"product_uuid": str(self.variant_product.uuid)}

        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertEqual(CartItem.objects.count(), 0)

    def test_cart_remove_item_not_in_cart(self):
        """Ensure that trying to remove an item that is not in the cart returns a 404 error."""
        self.client.force_authenticate(user=self.user)
        url = reverse('cart_remove_item')

        data = {"product_uuid": str(self.variant_product.uuid)}

        response = self.client.post(url, data, format='json')
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)
        self.assertEqual(response.data['error'], "Item not in cart")

    def test_cart_add_item_exseeds_initial_stock(self):
        """
        Verify that adding a quantity greater than the available stock 
        is blocked and returns a 400 Bad Request error.
        """
        self.client.force_authenticate(user=self.user)
        url = reverse("cart_add_item")

        data = {
            "product_uuid": str(self.variant_product.uuid),
            "quantity": 10
        }
        response = self.client.post(url, data, format="json")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("Insufficient stock", response.data["error"])
        # Ensure the item was NOT added to the database
        self.assertEqual(CartItem.objects.count(), 0)

    def test_cart_add_item_exceeds_accumulated_stock(self):
        """
        Ensure that incrementing an existing cart item's quantity 
        beyond the total available warehouse stock is blocked.
        """
        CartItem.objects.create(cart=self.cart, product=self.variant_product, quantity=9)

        self.client.force_authenticate(user=self.user)
        url = reverse("cart_add_item")

        data = {
            "product_uuid": str(self.variant_product.uuid),
            "quantity": 2
        }
        response = self.client.post(url, data, format="json")
        
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("Total available stock", response.data["error"])
        # Ensure the quantity in the database remained 4 and didn't update to 6
        self.assertEqual(CartItem.objects.first().quantity, 9)

    def test_cart_add_base_product_fails(self):
        """
        Verify that attempting to add a base (parent) product to the cart 
        is blocked and returns a 400 Bad Request error.
        """
        self.client.force_authenticate(user=self.user)
        url = reverse("cart_add_item")

        data = {
            "product_uuid": str(self.product1.uuid),
            "quantity": 2
        }

        response = self.client.post(url, data, format="json")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

        self.assertIn("Base products cannot be added to the cart", str(response.data))
